import mongoose from 'mongoose';

const communicationSchema = new mongoose.Schema({
  project: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Project',
    index: true
  },
  task: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task',
    index: true
  },
  subtask: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Subtask',
    index: true
  },
  type: {
    type: String,
    enum: {
      values: ['Email', 'Meeting', 'Call', 'Discussion'],
      message: 'Type must be one of: Email, Meeting, Call, Discussion'
    },
    required: [true, 'Communication type is required']
  },
  title: {
    type: String,
    required: [true, 'Communication title is required'],
    trim: true
  },
  summary: {
    type: String, // Can be generated by AI
    trim: true
  },
  details: {
    type: String, // Full meeting transcript, notes, or email body
    trim: true
  },
  participants: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  date: {
    type: Date,
    default: Date.now
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Communication log must have a creator']
  }
}, {
  timestamps: true
});

const Communication = mongoose.model('Communication', communicationSchema);
export default Communication;
